### ISSUE TITLE
北区深澜

### ISSUE THREAD

**Issue by yunyu930** [AdamXuD/2048Game#1]
大佬，近期新更新的北区深澜自动登录的那个库，我打算写一个推文教程发个人公众号，想获得一下你这边的授权，你看下这边方便不，可以以原作者的名义，或者我这边发布，分支到我的库里，不透露原作者

**Comment by AdamXuD** [comment]
可以的，不过这个脚本我只在我这边的环境测试过可用性，没在其他人的环境里测试过

**Comment by yunyu930** [comment]
谢谢大佬！我目前北区也没问题，其他区域也无所谓
